/**
 * File: src/ai/data/english/english_tokens.ts
 * Purpose: Domain-specific core tokens and tokenization hints for English domain.
 * This is a small seed of domain tokens useful for tokenizers, normalization and
 * simple seed-level embeddings.
 */

export const ENGLISH_CORE_TOKENS = [
  // reserved special tokens (recommended for model I/O)
  '[PAD]',
  '[UNK]',
  '[CLS]',
  '[SEP]',
  '[MASK]',

  // common high-frequency English tokens (seed)
  'the',
  'be',
  'to',
  'of',
  'and',
  'a',
  'in',
  'that',
  'have',
  'I',
  'it',
  'for',
  'not',
  'on',
  'with',

  // system/domain base tokens
  '<SYS_ENGLISH>',
  'ENGLISH_BASE',
  'ENGLISH_SYS_TOKEN',

  // numeric tokens (digits) - tokenizer will emit these for numeric characters
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',

  // additional numbered tokens to augment vocabulary determinism
  'TOKEN_10',
  'TOKEN_11',
  'TOKEN_12',
  'TOKEN_13',
  'TOKEN_14',
  'TOKEN_15',
  'TOKEN_16',
  'TOKEN_17',
  'TOKEN_18',
  'TOKEN_19',
  'TOKEN_20',
  'TOKEN_21',
  'TOKEN_22',
  'TOKEN_23',
  'TOKEN_24',
  'TOKEN_25',
  'TOKEN_26',
  'TOKEN_27',
  'TOKEN_28',
  'TOKEN_29',
  'TOKEN_30',
  'TOKEN_31',
  'TOKEN_32',
  'TOKEN_33',
  'TOKEN_34',
  'TOKEN_35',
  'TOKEN_36',
  'TOKEN_37',
  'TOKEN_38',
  'TOKEN_39',
  'TOKEN_40',
  'TOKEN_41',
  'TOKEN_42',
  'TOKEN_43',
  'TOKEN_44',
  'TOKEN_45',
  'TOKEN_46',
  'TOKEN_47',
  'TOKEN_48',
  'TOKEN_49',
  'TOKEN_50',
  'TOKEN_51',
  'TOKEN_52',
  'TOKEN_53',
  'TOKEN_54',
  'TOKEN_55',
  'TOKEN_56',
  'TOKEN_57',
  'TOKEN_58',
  'TOKEN_59',
  'TOKEN_60',
  'TOKEN_61',
  'TOKEN_62',
  'TOKEN_63',
];

export default ENGLISH_CORE_TOKENS;
